# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cdba15c6a932adbd4196b534fa6041958be9da3d600a0d1772a157bb17aeec861c314aaa4c1b8feb1b767e1c9a44f029d19eb8452c2a15a9bf1adcf94a6d110
  sendgrid_api_key: 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
  recaptcha_public_key: 6LfbCioUAAAAACyX5PYDG16-YbTBzaSwcmQEg82s
  recaptcha_private_key: 6LfbCioUAAAAAEZLi961xi0B3kCZrpmN9qdQMiDV 

test:
  secret_key_base: 307c7c263b84a9aa8475c54cbde1cc1cc427f74b167fc4300c6992bba985adcd0fef72a07cabec0364b6e40cdc2737f67349d9292f6efff9a21d9fcd726a157b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_api_key: <%= ENV["SENDGRID_KEY"] %>
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %> 
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %> 

